[module]
[module.hugoVersion]
min = "0.80.0"
extended = false

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.imports]]
path = "github.com/danielfdickinson/image-handling-mod-hugo-dfd"

[[module.imports]]
path = "github.com/danielfdickinson/metadata-mod-hugo-dfd"

